### ISSUE TITLE
[BUG]: Improve Customer Review UI

### ISSUE THREAD

**Issue by TenzDelek** [Indie-Kart/ecommerce-store#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current customer review UI need to have a change in terms of roundness and overall ui
<img width="1215" alt="image" src="https://github.com/Indie-Kart/ecommerce-store/assets/122612557/1536eb78-9fe5-4781-a859-215c351fa4e5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@TenzDelek Any Updates?
