### ISSUE TITLE
[Feature]: Want to Add floating Banner

### ISSUE THREAD

**Issue by Hardikchandra** [Indie-Kart/ecommerce-store#109]
### Describe the feature

want to add a floating with autorotating feature in place of this banner which increases user experience.

### Add ScreenShots

<img width="959" alt="image" src="https://github.com/Indie-Kart/ecommerce-store/assets/159153956/65dda001-910d-44ae-b811-d78788f9b376">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Hardikchandra** [comment]
@trishanu-init , its already present when i run it on local host .

**Comment by trishanu-init** [comment]
@Hardikchandra Can you make changes to make the feature functional on deployment?
