### ISSUE TITLE
[Feature]:ChatBot

### ISSUE THREAD

**Issue by happyrao78** [Indie-Kart/ecommerce-store#118]
### Describe the feature

Adding the personalized chatbot to the website using react library.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by happyrao78** [comment]
Kindly label it as level 3 because it will require a creation and logic of multiple files and components and then export to main page.

**Comment by happyrao78** [comment]
> Hello @happyrao78! Thanks for creating issue #118 on #Indie-Kart/ecommerce-store.Please Comment /assign-me to self assign this issue to yourself, and please don't forget to star this repo.

/assign-me

**Comment by trishanu-init** [comment]
Dear Contributor @happyrao78 ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.
