### ISSUE TITLE
[Feature]: add logo to the page

### ISSUE THREAD

**Issue by jayanththalla** [Indie-Kart/ecommerce-store#125]
### Describe the feature

there is no logo adding favicon

### Add ScreenShots

![image](https://github.com/Indie-Kart/ecommerce-store/assets/121346142/28fc6b3f-215d-44de-8d0f-a39864602dfe)
please assign me @pa
please label gssoc and add level

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @jayanththalla ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution. #

**Comment by HarshitGupta1511** [comment]
Please assign this issue to me @trishanu-init I want to work on this issue

**Comment by jayanththalla** [comment]
> This issue has been assigned to @jayanththalla for more than 5 days. Please provide an update.

yeah I am doing i will complete it please give some time
