### ISSUE TITLE
[Feature]: Add Scroll to Top Button

### ISSUE THREAD

**Issue by shakti177** [Indie-Kart/ecommerce-store#130]
### Describe the feature

I wish to add a Scroll to the Top button. Works best for mobile users

### Add ScreenShots

<img width="1436" alt="image" src="https://github.com/Indie-Kart/ecommerce-store/assets/57393413/a89ebf36-0c6d-4c44-b10b-6d4003bf5190">

No scroll to the top Button 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@kapilG0

**Comment by trishanu-init** [comment]
@shakti177 go ahead!

**Comment by shakti177** [comment]
shaktitamrakar@Shaktis-MacBook-Air ecommerce-store % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-google-login@5.2.2
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.7.15
npm ERR!   node_modules/@headlessui/react
npm ERR!     @headlessui/react@"^1.7.15" from the root project
npm ERR!   13 more (@react-oauth/google, @vercel/speed-insights, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16 || ^17" from react-google-login@5.2.2
npm ERR! node_modules/react-google-login
npm ERR!   react-google-login@"^5.2.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16 || ^17" from react-google-login@5.2.2
npm ERR!   node_modules/react-google-login
npm ERR!     react-google-login@"^5.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/shaktitamrakar/.npm/_logs/2024-06-21T14_36_34_684Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/shaktitamrakar/.npm/_logs/2024-06-21T14_36_34_684Z-debug-0.log
shaktitamrakar@Shaktis-MacBook-Air ecommerce-store % npm run dev

> ecommerce-front@0.1.0 dev
> next dev

sh: next: command not found
shaktitamrakar@Shaktis-MacBook-Air ecommerce-store % 

Getting this error

**Comment by TheNikhilRaj** [comment]
> shaktitamrakar@Shaktis-MacBook-Air ecommerce-store % npm install npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: react-google-login@5.2.2 npm ERR! Found: react@18.2.0 npm ERR! node_modules/react npm ERR! react@"^18.2.0" from the root project npm ERR! peer react@"^16 || ^17 || ^18" from @headlessui/react@1.7.15 npm ERR! node_modules/@headlessui/react npm ERR! @headlessui/react@"^1.7.15" from the root project npm ERR! 13 more (@react-oauth/google, @vercel/speed-insights, ...) npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^16 || ^17" from react-google-login@5.2.2 npm ERR! node_modules/react-google-login npm ERR! react-google-login@"^5.2.2" from the root project npm ERR! npm ERR! Conflicting peer dependency: react@17.0.2 npm ERR! node_modules/react npm ERR! peer react@"^16 || ^17" from react-google-login@5.2.2 npm ERR! node_modules/react-google-login npm ERR! react-google-login@"^5.2.2" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! npm ERR! For a full report see: npm ERR! /Users/shaktitamrakar/.npm/_logs/2024-06-21T14_36_34_684Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in: /Users/shaktitamrakar/.npm/_logs/2024-06-21T14_36_34_684Z-debug-0.log shaktitamrakar@Shaktis-MacBook-Air ecommerce-store % npm run dev
> 
> > ecommerce-front@0.1.0 dev
> > next dev
> 
> sh: next: command not found shaktitamrakar@Shaktis-MacBook-Air ecommerce-store %
> 
> Getting this error

@shakti177 @trishanu-init  Yes i also getting same error!

**Comment by shakti177** [comment]
I have got an error, and I have provided the error on the above chat.
