### ISSUE TITLE
[Feature]: Add a product reviews photo

### ISSUE THREAD

**Issue by DevGajjar28** [Indie-Kart/ecommerce-store#131]
### Describe the feature

Current product contain only one review photos. Add multiple photos of product so user can check it , This make a user to trust our website and user able so see every side of product.

### Add ScreenShots

![image](https://github.com/Indie-Kart/ecommerce-store/assets/145287513/045941a0-d5fe-4922-a50e-1e3eb641149d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ar7109** [comment]
@DevGajjar28 Please assign this issue to me under gssoc 2024
