### ISSUE TITLE
Add to Wishlist feature

### ISSUE THREAD

**Issue by Utsavladia** [Indie-Kart/ecommerce-store#132]
### Describe the feature

There should be a add to wishlist and view wishlist products option in the website.

I would love to add this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
You have been assigned.

**Comment by Utsavladia** [comment]
@trishanu-init  the add to cart functionality was not properly working at that time so i could not add this...
I hope is it fixed now and i can start working on it...

**Comment by trishanu-init** [comment]
It has been fixed
