### ISSUE TITLE
[Feature]: Add footer in the homepage

### ISSUE THREAD

**Issue by HarshitGupta1511** [Indie-Kart/ecommerce-store#133]
### Describe the feature

I want to add responsive footer in the homepage , which is usually  present in all shopping websites, this will make page more customised.

### Add ScreenShots

attaching a footer from shopping website for your reference.  please assign this task to me @trishanu-init 
<img width="1440" alt="Screenshot 2024-06-20 at 2 46 20 PM" src="https://github.com/Indie-Kart/ecommerce-store/assets/120268295/2651c00c-b16f-4a03-871c-ce181f896e84">
<img width="1440" alt="Screenshot 2024-06-20 at 2 49 38 PM" src="https://github.com/Indie-Kart/ecommerce-store/assets/120268295/261f05cd-0647-4e3d-b472-086c1dfc7b73">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshitGupta1511** [comment]
please assign this issue to me @trishanu-init

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@trishanu-init
