### ISSUE TITLE
Added sigin with google option and chnged style of signin and signup page

### ISSUE THREAD

**Issue by Krishna100604** [Indie-Kart/ecommerce-store#135]
### Describe the feature

![Screenshot (117)](https://github.com/Indie-Kart/ecommerce-store/assets/110299021/a9406a76-7a73-4126-9abd-d454b6361b54)
![Screenshot (116)](https://github.com/Indie-Kart/ecommerce-store/assets/110299021/29abddf6-c46a-4aef-b109-4e4e2d97a856)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Krishna100604** [comment]
@trishanu-init assign me this under Vsoc24

**Comment by Krishna100604** [comment]
@trishanu-init created pull request for the same and added screenshots there as well

**Comment by Krishna100604** [comment]
can you merge this i will create new pull request for that buttons in navbar

**Comment by Krishna100604** [comment]
can you give me points for this

**Comment by trishanu-init** [comment]
yes i have already done that
