### ISSUE TITLE
added login button and on clicking it routes through login page

### ISSUE THREAD

**Issue by Krishna100604** [Indie-Kart/ecommerce-store#152]
### Describe the feature

https://github.com/Indie-Kart/ecommerce-store/assets/110299021/4386f06f-9e68-4f5e-b658-d6a4cac7c98e

@trishanu-init  assign me again

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by Krishna100604** [comment]
@trishanu-init  give me the points

**Comment by trishanu-init** [comment]
@Krishna100604 I have already done that.....and post your point related queries on the discord channel from next time.

**Comment by Krishna100604** [comment]
> @Krishna100604 I have already done that.....and post your point related queries on the discord channel from next time.

okkk
