### ISSUE TITLE
[Feature]: Creating custom 404 not found page for the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Indie-Kart/ecommerce-store#154]
### Describe the feature

we can change it like we can add some images or gifs

### Add ScreenShots

![image](https://github.com/Indie-Kart/ecommerce-store/assets/125277258/59502bef-84d8-486a-8068-d6bc7eb2f004)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by Nishant-k-sagar** [comment]
I can make a simple static 404-error page for this website.
Kindly assign this issue to me @RamakrushnaBiswal

**Comment by trishanu-init** [comment]
@RamakrushnaBiswal go ahead!
