### ISSUE TITLE
[Feature]: Add Search Bar to navbar 

### ISSUE THREAD

**Issue by MinavKaria** [Indie-Kart/ecommerce-store#155]
### Describe the feature

I propose adding a search bar to the navbar for better user experience. I plan to do this in two PRs:

- Add the search bar component to the navbar.
- Implement the search functionality.

Please assign it to me

### Add ScreenShots

![image](https://github.com/Indie-Kart/ecommerce-store/assets/119132631/7f5ae74b-8324-470b-a62b-0e6ae3cfc405)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

@trishanu-init please assign this to me

**Comment by trishanu-init** [comment]
one feature should be associated with only one PR @MinavKaria

**Comment by MinavKaria** [comment]
Ok I'll try to do both , assign it to me

**Comment by trishanu-init** [comment]
Dear Contributor @MinavKaria  ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by MinavKaria** [comment]
Thanks a lot

**Comment by MinavKaria** [comment]
![image](https://github.com/Indie-Kart/ecommerce-store/assets/119132631/07806b07-838f-498f-8e5a-ea68755b6426)

@trishanu-init 
Looking proper ?

**Comment by trishanu-init** [comment]
Yes...and please change the suggestion text to something apparel related.
________________________________

**Comment by MinavKaria** [comment]
@trishanu-init I have sent the PR check that out

**Comment by MinavKaria** [comment]
@trishanu-init Acknowledge
