### ISSUE TITLE
[Feature]:Password toggling functionality

### ISSUE THREAD

**Issue by UtkarshBirla28** [Indie-Kart/ecommerce-store#156]
### Describe the feature

![Screenshot (85)](https://github.com/Indie-Kart/ecommerce-store/assets/96072228/bddd31e5-a4a8-4cb6-be7b-4bca8a97b1fd)

I want to add a password toggling functionality so that user can hide or view the password on clicking on the eye button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Okay @UtkarshBirla28...You have been assigned this isssue!

**Comment by RushilJalal** [comment]
@trishanu-init @UtkarshBirla28 No login form anymore. 
Kindly close this issue.

**Comment by UtkarshBirla28** [comment]
@RushilJalal what ? login form gayab ?
