### ISSUE TITLE
Adding Issue Template 

### ISSUE THREAD

**Issue by Niharika0104** [Indie-Kart/ecommerce-store#16]
By adding issue template,every will structure issue and the gist of the issue can be known easily.I will create that file and it becomes easy for the project maintainers to just look at the issues.

**Comment by trishanu-init** [comment]
Dear Contributor,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days of the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by trishanu-init** [comment]
@Niharika0104 Please link your issue with the PR's that you create.....i have updated the PULL_REQUEST_TEMPLATE.md.
You can go through that.
