### ISSUE TITLE
[BUG]: Typo in product page of all products

### ISSUE THREAD

**Issue by RushilJalal** [Indie-Kart/ecommerce-store#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As you can see in the screenshot, it says `color` when it should say `rating`
I checked and this issue persists in all products.

![image](https://github.com/Indie-Kart/ecommerce-store/assets/54212357/96cd9f2f-a357-4e62-bf34-1f0979f3ddb2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@RushilJalal go ahead!
