### ISSUE TITLE
[BUG]: Home page product image is very blurry

### ISSUE THREAD

**Issue by RushilJalal** [Indie-Kart/ecommerce-store#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A blurry image as soon as the user opens the website is not a good user experience.
I want to replace them with high quality pictures.

![image](https://github.com/Indie-Kart/ecommerce-store/assets/54212357/dbb76515-592a-4055-8b0f-d85f7349edfc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RushilJalal** [comment]
Kindly also provide the source of the current pictures.

**Comment by RushilJalal** [comment]
@trishanu-init why was this issue closed? The issue still exists on the site...

**Comment by trishanu-init** [comment]
@RushilJalal just need to use different images...it's not worth a issue!
