### ISSUE TITLE
[BUG]: Sign up button does nothing

### ISSUE THREAD

**Issue by RushilJalal** [Indie-Kart/ecommerce-store#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On going to sign up page at https://indiekart.vercel.app/login
I filled all details. On clicking the `Sign Up` button, nothing happens.

![image](https://github.com/Indie-Kart/ecommerce-store/assets/54212357/971ce390-3a98-4573-b9da-03953970e8e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@RushilJalal You have been assigned !

**Comment by RushilJalal** [comment]
@trishanu-init Currently the logic for sign up is just empty
I was reviewing my options for auth and came across [NextAuth](https://next-auth.js.org/)
Opinions?

**Comment by trishanu-init** [comment]
Yes you  can go ahead with NextAuth...if you need to discuss anything you can ping me on discord ".tri_n"

**Comment by RushilJalal** [comment]
@trishanu-init Kindly accept my request on discord. I have questions on the implementation

**Comment by RushilJalal** [comment]
@trishanu-init Kindly reply to my queries on Discord. I cannot make any changes until then.

**Comment by RushilJalal** [comment]
@trishanu-init https://github.com/RushilJalal/rushil-ecommerce-store 
Here's my repo where the sign up form works very well.
Kindly make changes if needed.
