### ISSUE TITLE
[BUG]: Remove Search Button in Search Bar

### ISSUE THREAD

**Issue by RushilJalal** [Indie-Kart/ecommerce-store#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, search button does nothing
You type something, the search bar shows results. You can click on any of the results to take you to the product. Here, clicking on the submit button does nothing.
Thus, I believe the button should be removed since it is redundant and misleading.

![image](https://github.com/Indie-Kart/ecommerce-store/assets/54212357/12645e4b-c152-4ccb-bed4-b03044e99075)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@RushilJalal Assigned !

**Comment by 01Dk01** [comment]
please assign me
