### ISSUE TITLE
Add Swiper insted of just banner

### ISSUE THREAD

**Issue by dhruv8433** [Indie-Kart/ecommerce-store#18]
@indie-Kart
@trishanu-init 
We can add swiper that autometically change banner of the website 
![image](https://github.com/Indie-Kart/ecommerce-store/assets/114583978/456c26b6-f2ab-4f35-82e2-05ec1efb260d)

something like this :
![image](https://github.com/Indie-Kart/ecommerce-store/assets/114583978/a21872f6-8547-41fc-a203-d5826105a3cc)

**Comment by AdhithiManjunath** [comment]
hey @Indie-Kart , i would like to work on this and add carousel as mentioned above . Thank you !!

**Comment by dhruv8433** [comment]
@trishanu-init 

thank you i will do my best
