### ISSUE TITLE
[BUG]: Chatbot will be hided

### ISSUE THREAD

**Issue by sivaprasath2004** [Indie-Kart/ecommerce-store#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this project `chatbot` can be hided.
- please assign me..

### Screenshot

![Screenshot from 2024-07-01 11-53-29](https://github.com/Indie-Kart/ecommerce-store/assets/121082414/aa3d15ae-20a3-4f58-8a36-4f51d2703b2c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RushilJalal** [comment]
@sivaprasath2004 You absolutely didn't search for existing issues.
There already exists an issue which has been assigned to me where I will remove the chatbot altogether.
Kindly check #179

**Comment by sivaprasath2004** [comment]
Thank you
