### ISSUE TITLE
[Feature]: `Share` options

### ISSUE THREAD

**Issue by sivaprasath2004** [Indie-Kart/ecommerce-store#189]
### Describe the feature

- In this project `product view` section we will click the `share` button that cannot share options.
- I want to implement to share options like `whatsApp` or other `social media`.
- please assign me...

### Add ScreenShots

[Screencast from 2024-07-01 20-27-15.webm](https://github.com/Indie-Kart/ecommerce-store/assets/121082414/5ca53c78-8695-406a-8342-73b114859f81)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by sivaprasath2004** [comment]
@trishanu-init  or @RushilJalal ,
please assign me..

**Comment by RushilJalal** [comment]
@sivaprasath2004 I'm not a maintainer here. Just a contributor.
The share button implements `Web Share API` https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API
It doesn't work on Firefox tho and I'm guessing not on Linux either.
It works for me on Chrome in Windows.

**Comment by trishanu-init** [comment]
@sivaprasath2004  You have been assigned !
