### ISSUE TITLE
Create Categorys

### ISSUE THREAD

**Issue by dhruv8433** [Indie-Kart/ecommerce-store#19]
@Indie-Kart
Instead of displaying direct product we can design category and on that category click we redirect user to seperate page of that category
![image](https://github.com/Indie-Kart/ecommerce-store/assets/114583978/eb85e4a2-f357-466e-b8ba-f9daae9cc08f)

something like this:
![image](https://github.com/Indie-Kart/ecommerce-store/assets/114583978/e6b07b6c-ea47-4b91-89c9-97d1d94238c3)

**Comment by trishanu-init** [comment]
This feature is already present
