### ISSUE TITLE
[Feature]: Enhanced Product Categorization and Filtering

### ISSUE THREAD

**Issue by Pratham-Vishwakarma** [Indie-Kart/ecommerce-store#200]
### Describe the feature

 Description: Enhance the user experience by implementing advanced product categorization and filtering options on the website.

• Category Segregation:
Create distinct categories for Men, Women, and Kids. Each category should have its own dedicated section on the website.

• Size Filtering:
Implement size filters within each category. Users should be able to filter products based on available sizes categories, colors, and prices (e.g., XS, S, M, L, XL).

• Color Filtering:
Add color filtering options, allowing users to select products based on their preferred available colors.

• Multiple Filter Combinations:
Ensure that users can apply multiple filters simultaneously while purchasing (e.g., Men’s T-shirts in size M and color blue).

### Add ScreenShots

![Screenshot (39)](https://github.com/Indie-Kart/ecommerce-store/assets/147902380/c797d74f-f70d-41a6-8742-18f9d67b12eb)
This Area Will Be Updated.

![Screenshot (43)](https://github.com/Indie-Kart/ecommerce-store/assets/147902380/5f201996-c918-42bb-ab4e-1ab8d712ffcb)
This Area Will Be  Updated.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@Pratham-Vishwakarma All these features are already there.....check out https://indiekart-admin.vercel.app/
