### ISSUE TITLE
[Feature]: Add a Sign-In Page

### ISSUE THREAD

**Issue by Pratham-Vishwakarma** [Indie-Kart/ecommerce-store#201]
### Describe the feature

Create a dedicated sign-in page for users to log in to their accounts. This page should provide a seamless and secure way for users to access their profiles and personalized features.

### Add ScreenShots

![Screenshot (40)](https://github.com/Indie-Kart/ecommerce-store/assets/147902380/32450924-a578-45f1-a6e9-433a41724761)
This Page Will Be Updated

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@Pratham-Vishwakarma  Github OAuth signIn is present but not yet deployed !!
