### ISSUE TITLE
[BUG]: Change the style of Cursor 

### ISSUE THREAD

**Issue by trishanu-init** [Indie-Kart/ecommerce-store#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current cursor style on the store does not align with the design and theme of the website. A more subtle cursor style is preferred.

![image](https://github.com/Indie-Kart/ecommerce-store/assets/85580785/df1f9f6f-f260-48a9-8f60-27c938c20cc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MastanSayyad** [comment]
Hey @trishanu-init 

I would like to work on this task as I have prior experience for it Could you please assign this issue to me?

**Some examples of my works are:**


https://github.com/Indie-Kart/ecommerce-store/assets/101971980/9d9e741e-065e-4f65-893a-9a01b8ecba54


https://github.com/Indie-Kart/ecommerce-store/assets/101971980/2ec1964f-6ce8-4029-86f7-62d5df520211

**Comment by trishanu-init** [comment]
@MastanSayyad Assigned to you!
