### ISSUE TITLE
[BUG]: Cart page item removed prize not change

### ISSUE THREAD

**Issue by sivaprasath2004** [Indie-Kart/ecommerce-store#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this project `Cart` page  i will try to product remove the prize cannot reduce .
- please assign me..

### Video

[Screencast from 2024-07-07 08-03-21.webm](https://github.com/Indie-Kart/ecommerce-store/assets/121082414/b081c7c0-1626-409a-9d44-702528aa5bb9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@sivaprasath2004 Assigned
