### ISSUE TITLE
[Feature]: Enhance Readme.md

### ISSUE THREAD

**Issue by ananyag309** [Indie-Kart/ecommerce-store#215]
### Describe the feature

I would like to link LISENCE file to main readme file. moreover i am aiming to enhance readme.md under gssoc by adding a feature in section, table of content, adding animation etc.
Why feature in section? - Feature in section will highlight that the project was part of gssoc in more clean, neat and representable form. I have added ss for the same, will try to create similar.
Table of content so that user have a easy navigation throughout the file

### Add ScreenShots

![readmee](https://github.com/Indie-Kart/ecommerce-store/assets/145869907/eef420b5-9489-489b-8ecd-db8eaff71ccd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
@ananyag309 assigned
