### ISSUE TITLE
Make Dropdown close automatically on choosing any option on it

### ISSUE THREAD

**Issue by Utsavladia** [Indie-Kart/ecommerce-store#225]
### Describe the feature

Dropdown should close automatically on choosing any option on it to enhance the user experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/34590ca1-d9d3-4a4e-a03b-ac485420ef23)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

**Comment by Utsavladia** [comment]
This is under GSSOC but the VSOC option is made required for submitting the issue...

**Comment by trishanu-init** [comment]
@Utsavladia Assigned !
