### ISSUE TITLE
Add Lazy-Loading to the Web-Page.

### ISSUE THREAD

**Issue by ritankarsaha** [Indie-Kart/ecommerce-store#28]
### Describe the feature

I will add Lazy-Loading to the webpgae. This will ensure that as the user scrolls down, the website will be loaded correspondingly. This provides a better UI for the web-page and user interactivity.

### Add ScreenShots

<img width="1050" alt="Screenshot 2024-05-16 at 2 45 11 AM" src="https://github.com/Indie-Kart/ecommerce-store/assets/136831315/6f70c027-a996-4cf8-9ddb-ea256847e550">
<img width="1050" alt="Screenshot 2024-05-16 at 2 44 52 AM" src="https://github.com/Indie-Kart/ecommerce-store/assets/136831315/18d2f3e4-b9b9-44cd-aae0-e5962d1ea676">
While scolling down, the page will lazy-load instead of loading instantly.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ritankarsaha** [comment]
Please assign this issue to me under #gssoc'24. Please also add labels- 'GSSOC' and 'level'.

**Comment by trishanu-init** [comment]
Dear Contributor,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.
