### ISSUE TITLE
DARKMODE_[Feature]:

### ISSUE THREAD

**Issue by Meetjain1** [Indie-Kart/ecommerce-store#47]
### Describe the feature

Adding darkmode feature to our current website can make our website to look more good and can provide better user friendly experience @trishanu-init assign this issue to me I will add this feature .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Meetjain1** [comment]
assign-me

**Comment by trishanu-init** [comment]
@Meetjain1 Follow the issue template before creating an issue

**Comment by Meetjain1** [comment]
> @Meetjain1 Follow the issue template before creating an issue

I just removed the non-required field.

**Comment by nishant0708** [comment]
can you assign me this issue under gssoc 24.

**Comment by Meetjain1** [comment]
> /assign-me
@Ujjwal-2910 
You were not asked to write this ok !
Why are u doing these type of cheap practices ??

**Comment by trishanu-init** [comment]
@Meetjain1  First create PR's for the issues assigned to you , don't spam by claiming multiple issues.
