### ISSUE TITLE
Navbar not fixed_[BUG]:

### ISSUE THREAD

**Issue by Meetjain1** [Indie-Kart/ecommerce-store#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If we fix the navbar in our current website , It will provide better user-friendly experience 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
can you assign me this issue under gssoc 24.
