### ISSUE TITLE
No option to choose the size

### ISSUE THREAD

**Issue by Utsavladia** [Indie-Kart/ecommerce-store#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The option to choose the size is not available.

There should be a dropdown or size slabs to choose the desired one.
![Screenshot 2024-05-25 230949](https://github.com/Indie-Kart/ecommerce-store/assets/124615886/74b7cd34-c9ea-4d6f-ab00-a030165a2fb9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @Utsavladia ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by Utsavladia** [comment]
Thank you. I will try to finish it within deadline.😊

**Comment by Utsavladia** [comment]
@trishanu-init 
I have made a pull reqeuest for this issue 
kindlly update me about it because it got closed...

**Comment by trishanu-init** [comment]
option is already present thst is why it has been closed
