### ISSUE TITLE
The navbar should be fixed at top

### ISSUE THREAD

**Issue by Utsavladia** [Indie-Kart/ecommerce-store#53]
### Describe the feature

The navbar should be fixed at the top of page and should not scroll with the page scrolling

### Add ScreenShots

![image](https://github.com/Indie-Kart/ecommerce-store/assets/124615886/20b08335-ea57-400f-a009-60f2fb371ac4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @Utsavladia ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by Utsavladia** [comment]
thank you for giving me this opportunity. I will try to complete it within deadline.

**Comment by Utsavladia** [comment]
@trishanu-init 
thank you for giving me this opportunity. I will try to complete it within deadline.
