### ISSUE TITLE
Adding the tilty effect to cards, animated cursor and customer reviews.

### ISSUE THREAD

**Issue by happyrao78** [Indie-Kart/ecommerce-store#55]
### Describe the feature

Animated Cursor:
Adding the animated cursor to improve the scrolling and cursing effect on different pages.
Tilty Effect:
Adding the tilty efffect on home cards and open source sections.
Customer reviews:
adding the customer eview section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @happyrao78 ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.
