### ISSUE TITLE
[Feature]: Adding a Hamburger menu for small devices in navbar .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Indie-Kart/ecommerce-store#62]
### Describe the feature

Adding a hamburger menu to the website for small devices will make it responsive .

### Add ScreenShots
![Screenshot 2024-05-28 152812](https://github.com/Indie-Kart/ecommerce-store/assets/118350936/eb61432e-9f38-4d82-8c2b-2dcb7b9b3da4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @Ayushmaanagarwal1211 ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by Ayushmaanagarwal1211** [comment]
Sure
