### ISSUE TITLE
[BUG]: update empty state of cart

### ISSUE THREAD

**Issue by dhruv8433** [Indie-Kart/ecommerce-store#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Indie-Kart
@trishanu-init 

check this out, 
![image](https://github.com/Indie-Kart/ecommerce-store/assets/114583978/d90b5509-9fba-4c71-956b-008a44ecea50)

we can update empty state of cart something like this,
![image](https://github.com/Indie-Kart/ecommerce-store/assets/114583978/21ebcd05-9cf3-44f2-9181-1026a112afcc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @dhruv8433 ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by dhruv8433** [comment]
@trishanu-init 

thank you i will try my best
