### ISSUE TITLE
[Feature]: Change Currency from $ to INR or ₹

### ISSUE THREAD

**Issue by trishanu-init** [Indie-Kart/ecommerce-store#66]
The current default currency for all products listed on the store is set to $. It may be beneficial to change this to INR or ₹ to ensure that the pricing is geographically accurate.

**Comment by avayyyyyyy** [comment]
want both pricing or just INR? @trishanu-init

**Comment by trishanu-init** [comment]
> want both pricing or just INR? @trishanu-init

only INR "₹"

**Comment by avayyyyyyy** [comment]
okayy assign it me! i can work on this issue @trishanu-init

**Comment by UtkarshBirla28** [comment]
assign it to me! i will work on it
 @trishanu-init

**Comment by trishanu-init** [comment]
@avayyyyyyy I am assigning this to you.Please revert back with acknowledgment.

**Comment by UtkarshBirla28** [comment]
@trishanu-init Assign it to me sir i will resolve it ASAP

**Comment by trishanu-init** [comment]
@UtkarshBirla28 You have been assigned !!

**Comment by UtkarshBirla28** [comment]
![Screenshot (150)](https://github.com/Indie-Kart/ecommerce-store/assets/96072228/ffdb8c58-46c3-4b28-9618-a02687e1034b)

@trishanu-init is this good sir ?

**Comment by UtkarshBirla28** [comment]
@or should i calculate it i mean if something is for $500 then i should calculate it by doing some calculation like 500*83.49 =41745 

but 41 k is toomuch :) for a T-Shirt

**Comment by trishanu-init** [comment]
@UtkarshBirla28 Please create a pull request and push a commit so that I can review the changes!!
