### ISSUE TITLE
feat: Integrating search bar on navbar

### ISSUE THREAD

**Issue by Niharika0104** [Indie-Kart/ecommerce-store#7]
# Embedding Search Bar on Navbar for Product Search by Category

### Problem Statement
We need to enhance user experience by embedding a search bar on the navbar, allowing users to search for products based on category directly from any page.

### Proposed Solution
1. Integrate a search bar into the navbar.
2. Enable users to enter search queries.
3. Implement functionality to filter search results by category.
4. Display search results in a user-friendly format.

### Additional Features
- **Autocomplete Suggestions:** Provide autocomplete suggestions as users type in the search bar to enhance usability.
- **Responsive Design:** Ensure the search bar is responsive and works seamlessly across all devices and screen sizes.

### UI/UX Considerations
- **Positioning:** Determine the optimal position for the search bar in the navbar to maximize visibility and accessibility.
- **Styling:** Maintain consistency with the existing navbar design while making the search bar visually prominent.

## Priority
 Medium,

## Labels
- enhancement
- search
- navbar
- category

**Comment by trishanu-init** [comment]
@Niharika0104 I have assigned this issue to you.
Happy Contributing !! 😃

**Comment by Niharika0104** [comment]
@trishanu-init Do I have to create a backend route for this or just the ui will be sufficient?

**Comment by trishanu-init** [comment]
> @trishanu-init Do I have to create a backend route for this or just the ui will be sufficient?

Yes! Just the ui is not sufficient.

**Comment by Asymtode712** [comment]
@trishanu-init can you please assign me this issue as it's been inactivity for more than 20 days and I wish to work on it

**Comment by Niharika0104** [comment]
I will update by tomorrow on this

**Comment by Asymtode712** [comment]
@trishanu-init can you reopen and please assign me this issue, I wish to work on it

**Comment by trishanu-init** [comment]
this feature has been implemented already @Asymtode712 ,please find some other issue
