### ISSUE TITLE
directly removed cart from cart page

### ISSUE THREAD

**Issue by kushalkumar1362** [Indie-Kart/ecommerce-store#72]
### Describe the feature

I get frustrated when I have to visit the Add to Cart page to remove an item, as it makes managing items time-consuming. For instance, if I accidentally bookmark a product, I need to go to the cart page, locate the product, and then remove it. This process is not user-friendly and could be improved.

"I would like to have the ability to remove items directly from the item page. I suggest adding a 'Remove item' button. When a product is added to the cart, the 'add to cart' button should be replaced with a 'remove from cart' button, allowing users to quickly and easily remove the item if needed."

### Add ScreenShots

![Screenshot (368)](https://github.com/Indie-Kart/ecommerce-store/assets/140513098/a5007194-fa22-4d7e-a5fd-e174dbc7eb48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Dear Contributor @kushalkumar1362 ,
You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

**Comment by kushalkumar1362** [comment]
> Dear Contributor @kushalkumar1362 , You have been assigned this issue. As you begin working on the assigned issue, please ensure that you follow the contributing guidelines closely. This will help maintain the quality and consistency of the project. If a Pull Request (PR) is not created within 5 days from the issue assignment, the issue will be reassigned. We appreciate your understanding and look forward to your valuable contribution.

 Agreed, Thank you for assigning me this task
