### ISSUE TITLE
[Feature]:Share option

### ISSUE THREAD

**Issue by Rohitha-pudu** [Indie-Kart/ecommerce-store#77]
### Describe the feature

share button to share the items 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Share Button should be functional just ui is not sufficient

**Comment by Rohitha-pudu** [comment]
> Share Button should be functional just ui is not sufficient

Ok I will try to do it

**Comment by ShampaShaw** [comment]
assign me this issue under gssoc'24
