### ISSUE TITLE
[Feature]:Prices Filter

### ISSUE THREAD

**Issue by Rohitha-pudu** [Indie-Kart/ecommerce-store#84]
### Describe the feature

Filter option and its functionality on prices

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trishanu-init** [comment]
Please be more detailed

**Comment by ShampaShaw** [comment]
assign me this issue under gssoc'24
