### ISSUE TITLE
[Feature]: build an the about us page for  the website 

### ISSUE THREAD

**Issue by CoderSwarup** [Indie-Kart/ecommerce-store#91]
### Describe the feature

We want to build the About us page for the website where the list of all the contributors data will be display  

showing the details of the Repo contributors and some info about the website 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
Hey can i work on this issue?
